---
# - platform: knx
#   name: EG Wohnen Luftfeuchte rel
#   state_address: '5/2/4'
#   type: 'percent'
# - platform: knx
#   name: OG Kind I Luftfeuchte rel
#   state_address: '5/2/20'
#   type: 'percent'
# - platform: knx
#   name: OG Bad Luftfeuchte rel
#   state_address: '5/2/25'
#   type: 'percent'
# - platform: knx
#   name: OG Schlafen Luftfeuchte rel
#   state_address: '5/2/27'
#   type: 'percent'
# - platform: knx
#   name: Dach Luftfeuchte rel
#   state_address: '5/2/30'
#   type: 'percent'
# - platform: knx
#   name: Aussen Luftfeuchte rel
#   state_address: '5/2/40'
#   type: 'percent'

# - platform: knx
#   name: EG Wohnen Luftfeuchte abs
#   state_address: '5/2/104'
#   type: '4byte_float'
# - platform: knx
#   name: OG Kind I Luftfeuchte abs
#   state_address: '5/2/120'
#   type: '4byte_float'
# - platform: knx
#   name: OG Bad Luftfeuchte abs
#   state_address: '5/2/125'
#   type: '4byte_float'
# - platform: knx
#   name: OG Schlafen Luftfeuchte abs
#   state_address: '5/2/127'
#   type: '4byte_float'
# - platform: knx
#   name: Dach Luftfeuchte abs
#   state_address: '5/2/130'
#   type: '4byte_float'
# - platform: knx
#   name: Aussen Luftfeuchte abs
#   state_address: '5/2/140'
#   type: '4byte_float'

- platform: knx
  name: Temperatur EG HAR
  state_address: '5/3/0'
  type: 'temperature'
- platform: knx
  name: Temperatur EG Bad
  state_address: '5/3/1'
  type: 'temperature'
- platform: knx
  name: Temperatur EG Arbeiten
  state_address: '5/3/2'
  type: 'temperature'
- platform: knx
  name: Temperatur EG Essen
  state_address: '5/3/3'
  type: 'temperature'
- platform: knx
  name: Temperatur EG Wohnen
  state_address: '5/3/4'
  type: 'temperature'
- platform: knx
  name: Temperatur EG Flur
  state_address: '5/3/5'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Kind I
  state_address: '5/3/20'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Kind II
  state_address: '5/3/22'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Bad
  state_address: '5/3/24'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Ankleide
  state_address: '5/3/26'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Schlafen
  state_address: '5/3/27'
  type: 'temperature'
- platform: knx
  name: Temperatur OG Flur
  state_address: '5/3/29'
  type: 'temperature'
# - platform: knx
#   name: Temperatur Dach
#   state_address: '5/3/30'
#   type: 'temperature'
# - platform: knx
#   name: Temperatur Aussen Fassade N
#   state_address: '5/3/40'
#   type: 'temperature'
- platform: knx
  name: Temperatur Aussen WS
  state_address: '5/3/41'
  type: 'temperature'

- platform: knx
  name: Windgeschwindigkeit
  state_address: '5/0/5'
  type: 'wind_speed_ms'

- platform: knx
  name: Helligkeit EG Bad
  state_address: '5/4/0'
  type: 'illuminance'
- platform: knx
  name: Helligkeit EG Flur
  state_address: '5/4/4'
  type: 'illuminance'
- platform: knx
  name: Helligkeit OG Bad
  state_address: '5/4/7'
  type: 'illuminance'
- platform: knx
  name: Helligkeit OG Ankleide
  state_address: '5/4/8'
  type: 'illuminance'
- platform: knx
  name: Helligkeit OG Flur
  state_address: '5/4/10'
  type: 'illuminance'
- platform: knx
  name: Helligkeit Fassade O
  state_address: '5/4/11'
  type: 'illuminance'
- platform: knx
  name: Helligkeit Fassade S
  state_address: '5/4/12'
  type: 'illuminance'
- platform: knx
  name: Helligkeit Fassade W
  state_address: '5/4/13'
  type: 'illuminance'
- platform: knx
  name: Helligkeit Carport
  state_address: '5/4/15'
  type: 'illuminance'