
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 300
  unit_system: metric
  time_zone: Europe/Berlin
  name: Home
  customize: !include customize.yaml

automation: !include_dir_merge_list automations

binary_sensor: !include_dir_merge_list entities/binary_sensors

# https://www.home-assistant.io/integrations/caldav/
calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: !secret caldav_url

# https://www.nabucasa.com/config/
cloud:

cover: !include_dir_merge_list entities/covers

# https://www.home-assistant.io/integrations/discovery/
discovery:
  ignore:
    - homekit
    - sonos

# https://www.home-assistant.io/integrations/frontend/
frontend:
  javascript_version: auto
  themes: !include_dir_merge_named themes

group: !include_dir_merge_list entities/groups

# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_proxies: !secret http_trusted_proxies

input_boolean: !include entities/input_boolean.yaml

knx: !include knx.yaml

light: !include_dir_merge_list entities/lights

logger:
  default: warning
  logs:
    xknx: warning

# https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

person: !include entities/persons.yaml
recorder: !include recorder.yaml
rest_command: !include entities/rest_command.yaml
scene: !include entities/scenes.yaml
script: !include entities/scripts.yaml

sensor: !include_dir_merge_list entities/sensors

# https://www.home-assistant.io/integrations/sonos/
sonos: 
  media_player:
    hosts: !secret sonos_hosts

switch: !include_dir_merge_list entities/switches

# https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate
    language: 'de'

# https://www.home-assistant.io/integrations/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    #name: !secret darksky_name
    mode: daily

webostv:
  host: !secret lgtv_ip
  name: TV Schlafen

#zone: !include_dir_list entities/zones