---
title: Home
excluded_entities: null
background: var(--background-image)

views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/light.yaml
  - !include lovelace/views/cover.yaml
  - !include lovelace/views/socket.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/humidity.yaml
  - !include lovelace/views/window.yaml
  - !include lovelace/views/mediaplayer.yaml