---
- platform: knx
  name: EG HAR
  move_long_address:      '2/1/0'
  move_short_address:     '2/2/0'
  position_address:       '2/4/0'
  position_state_address: '2/5/0'
- platform: knx
  name: EG Bad
  move_long_address:      '2/1/1'
  move_short_address:     '2/2/2'
  position_address:       '2/4/1'
  position_state_address: '2/5/1'
- platform: knx
  name: EG Arbeiten S
  move_long_address:      '2/1/2'
  move_short_address:     '2/2/2'
  position_address:       '2/4/2'
  position_state_address: '2/5/2'
- platform: knx
  name: EG Arbeiten W
  move_long_address:      '2/1/3'
  move_short_address:     '2/2/3'
  position_address:       '2/4/3'
  position_state_address: '2/5/3'
- platform: knx
  name: EG Kueche
  move_long_address: '2/1/4'
  move_short_address: '2/2/4'
  position_address: '2/4/4'
  position_state_address: '2/5/4'
- platform: knx
  name: EG Essen
  move_long_address: '2/1/5'
  move_short_address: '2/2/5'
  position_address: '2/4/5'
  position_state_address: '2/5/5'
- platform: knx
  name: EG Wohnen L
  move_long_address: '2/1/6'
  move_short_address: '2/2/6'
  position_address: '2/4/6'
  position_state_address: '2/5/6'
- platform: knx
  name: EG Wohnen R
  move_long_address: '2/1/7'
  move_short_address: '2/2/7'
  position_address: '2/4/7'
  position_state_address: '2/5/7'
- platform: knx
  name: OG Kind I O
  move_long_address: '2/1/8'
  move_short_address: '2/2/8'
  position_address: '2/4/8'
  position_state_address: '2/5/8'
- platform: knx
  name: OG Kind I S
  move_long_address: '2/1/9'
  move_short_address: '2/2/9'
  position_address: '2/4/9'
  position_state_address: '2/5/9'
- platform: knx
  name: OG Kind II S
  move_long_address: '2/1/10'
  move_short_address: '2/2/10'
  position_address: '2/4/10'
  position_state_address: '2/5/10'
- platform: knx
  name: OG Kind II W
  move_long_address: '2/1/11'
  move_short_address: '2/2/11'
  position_address: '2/4/11'
  position_state_address: '2/5/11'
- platform: knx
  name: OG Bad
  move_long_address: '2/1/12'
  move_short_address: '2/2/12'
  position_address: '2/4/12'
  position_state_address: '2/5/12'
- platform: knx
  name: OG Ankleide
  move_long_address: '2/1/13'
  move_short_address: '2/2/13'
  position_address: '2/4/13'
  position_state_address: '2/5/13'
- platform: knx
  name: OG Schlafen N
  move_long_address: '2/1/14'
  move_short_address: '2/2/14'
  position_address: '2/4/14'
  position_state_address: '2/5/14'
- platform: knx
  name: OG Schlafen O
  move_long_address: '2/1/15'
  move_short_address: '2/2/15'
  position_address: '2/4/15'
  position_state_address: '2/5/15'
- platform: knx
  name: OG Treppe
  move_long_address: '2/1/16'
  move_short_address: '2/2/16'
  position_address: '2/4/16'
  position_state_address: '2/5/16'