---
- platform: knx
  name: Fenster EG HAR
  state_address: '2/7/0'
  device_class: window
- platform: knx
  name: Fenster EG Bad
  state_address: '2/7/1'
  device_class: window
- platform: knx
  name: Fenster EG Arbeiten S
  state_address: '2/7/2'
  device_class: window
- platform: knx
  name: Fenster EG Arbeiten W
  state_address: '2/7/3'
  device_class: window
- platform: knx
  name: Fenster EG Kueche
  state_address: '2/7/4'
  device_class: window
- platform: knx
  name: Tuer EG Essen
  state_address: '2/7/5'
  device_class: door
- platform: knx
  name: Tuer EG Wohnen L
  state_address: '2/7/6'
  device_class: door
- platform: knx
  name: Tuer EG Wohnen R
  state_address: '2/7/7'
  device_class: door
- platform: knx
  name: Tuer EG Abstellkammer
  state_address: '2/7/8'
  device_class: door
- platform: knx
  name: Haustuer
  state_address: '2/7/9'
  device_class: door
- platform: knx
  name: OG Dachluke
  state_address: '2/7/10'
  device_class: opening
- platform: knx
  name: Tag Nacht
  state_address: '5/0/2'
- platform: knx
  name: Bewegung EG Flur
  state_address: '5/5/6'
- platform: knx
  name: Steinel Licht schalten
  state_address: '5/7/0'
- platform: knx
  name: Steinel Entfernung 1
  state_address: '5/7/2'
- platform: knx
  name: Steinel Bewegung links
  state_address: '5/7/3'
- platform: knx
  name: Steinel Bewegung frontal
  state_address: '5/7/4'
- platform: knx
  name: Steinel Bewegung rechts
  state_address: '5/7/5'