---

- alias: 'Change theme'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.tag_nacht
      to: 'on'
    - platform: state
      entity_id: binary_sensor.tag_nacht
      to: 'off'
  action:
    - service: frontend.set_theme
      data_template:
        name: >
          {% if states.binary_sensor.tag_nacht.state == "on" %}
            Google Light Theme
          {% else %}
            Google Dark Theme
          {% endif %}