---

# set default theme on day
- alias: set_theme_day
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: state
    entity_id: binary_sensor.tag_nacht
    state: 'on'
  action:
    service: frontend.set_theme
    data:
      name: default

# set dark theme on night
- alias: set_theme_night
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: state
    entity_id: binary_sensor.tag_nacht
    state: 'off'
  action:
    service: frontend.set_theme
    data:
      name: 'Google Dark Theme'