---

# Close Cover when TV is tuned on
- alias: LGTV Close Cover Day
  trigger:
    platform: state
    entity_id: media_player.tv_schlafen
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.tag_nacht
    state: 'on'
  action:
    service: cover.close_cover
    entity_id: cover.og_schlafen_n

- alias: LGTV Close Cover Night
  trigger:
    platform: state
    entity_id: media_player.tv_schlafen
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.tag_nacht
    state: 'off'
  action:
    - service: cover.close_cover
      entity_id: cover.og_schlafen_n
    - service: cover.set_cover_position
      data:
        entity_id: cover.og_schlafen_o
        position: 30
    - service: light.turn_on
      entity_id: light.og_schlafen_tv

# Open Cover when TV is turned off
- alias: LGTV Open Cover
  trigger:
    platform: state
    entity_id: media_player.tv_schlafen
    to: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.og_schlafen_n
    - service: cover.open_cover
      entity_id: cover.og_schlafen_o
    - service: light.turn_off
      entity_id: light.og_schlafen_tv