---
sensor:
  - platform: template
    sensors:

      hpsu_mode2:
        friendly_name: "HPSU Modus"
        value_template: >-
          {% if is_state('sensor.hpsu_mode', '0') %}
            Aus
          {% elif is_state('sensor.hpsu_mode', '1') %}
            Heizen
          {% elif is_state('sensor.hpsu_mode', '2') %}
            Kuehlen
          {% elif is_state('sensor.hpsu_mode', '4') %}
            Warmwasser
          {% elif is_state('sensor.hpsu_mode', '3') %}
            Enteisen
          {% else %}
            unknown
          {% endif %}

      # Template Sensors to send Sonos values to KNX bus
      sonos_og_bad_volume:
        value_template: "{{ state_attr('media_player.bad', 'volume_level') * 100 }}"
      sonos_og_bad_state:
        value_template: >- 
          {% if is_state('media_player.bad', 'playing') %}
            on
          {% else %}
            off
          {% endif %}