---
sensor:
  - platform: template
    sensors:
      hpsu_mode2:
        friendly_name: "HPSU Modus"
        value_template: >-
          {% if is_state('sensor.hpsu_mode', '0') %}
            Aus
          {% elif is_state('sensor.hpsu_mode', '1') %}
            Heizen
          {% elif is_state('sensor.hpsu_mode', '2') %}
            Kuehlen
          {% elif is_state('sensor.hpsu_mode', '4') %}
            Warmwasser
          {% elif is_state('sensor.hpsu_mode', '3') %}
            Enteisen
          {% else %}
            unknown
          {% endif %} 